export const GET_ERRORS = 'GET_ERRORS';
export const CLEAR_ERRORS = 'CLEAR_ERRORS';


export const GET_PRODUCTS = 'GET_PRODUCTS';
export const GET_CAT_PRODUCTS = 'GET_CAT_PRODUCTS';
export const GET_PRODUCT = 'GET_PRODUCT';
export const GET_DIS_PRODUCT = 'GET_DIS_PRODUCT';
export const GET_CAT_PRODUCT = 'GET_CAT_PRODUCT';
export const UNMOUNT_PRODUCTS = 'UNMOUNT_PRODUCTS';

export const GET_CATEGORIES = 'GET_CATEGORIES';
export const GET_PROCATEGORIES = 'GET_PROCATEGORIES';

export const SET_CURRENT_USER = 'SET_CURRENT_USER';
export const GET_PROFILE = 'GET_PROFILE';
export const PROFILE_LOADING = 'PROFILE_LOADING';
export const CLEAR_PROFILE = 'CLEAR_PROFILE';
export const GET_DASHBOARD = 'GET_DASHBOARD';
export const GET_DM = 'GET_DM';
export const GET_TRANSFERS = 'GET_TRANSFERS';
export const GET_CENTRAL = 'GET_CENTRAL';

export const GET_DIVISION = 'GET_DIVISION';
export const GET_DISTRICT = 'GET_DISTRICT';
export const PLACE_LOADING = 'PLACE_LOADING';

export const RESTORE_CART = 'RESTORE_CART';
export const SUBMIT_CART = 'SUBMIT_CART';
export const ADD_CART_PRODUCT = 'ADD_CART_PRODUCT';
export const DELETE_CART_PRODUCT = 'DELETE_CART_PRODUCT';
export const CART_MESSAGE = 'CART_MESSAGE';
export const ADD_CART_PRODUCT_QTY = 'ADD_CART_PRODUCT_QTY';
export const MINUS_CART_PRODUCT_QTY = 'MINUS_CART_PRODUCT_QTY';
export const GET_STORAGE = 'GET_STORAGE';
export const GET_WARHOUSE = 'GET_WARHOUSE';
export const GET_SEARCH = 'GET_SEARCH';